### ISSUE TITLE
Bug: System.Configuration.ConfigurationErrorsException: Failed to save settings: Unable to save config to file 'C:\Users\matth\AppData\Local\AnyStatus\anystatus.desktop.exe_StrongName_t5dzl52jcd1fnyp34mfu0q5i0vqilrtv\1.0.0.0\user.config

### ISSUE THREAD

**Issue by MatthewSteeples** [AnyStatus/Support#115]
Happens when trying to Import settings or Reset to default. Application needs to be force closed as the exception prevents the exit of the application. Just about to see if restarting the computer solves the problem. I've got a full memory dump file saved if you want that sending through privately.

Full Stack Trace

```
[12:22:57.442] System.Configuration.ConfigurationErrorsException: Failed to save settings: Unable to save config to file 'C:\Users\matth\AppData\Local\AnyStatus\anystatus.desktop.exe_StrongName_t5dzl52jcd1fnyp34mfu0q5i0vqilrtv\1.0.0.0\user.config'. ---> System.Configuration.ConfigurationErrorsException: Unable to save config to file 'C:\Users\matth\AppData\Local\AnyStatus\anystatus.desktop.exe_StrongName_t5dzl52jcd1fnyp34mfu0q5i0vqilrtv\1.0.0.0\user.config'.
   at System.Configuration.Internal.WriteFileContext.ReplaceFile(String Source, String Target)
   at System.Configuration.Internal.WriteFileContext.Complete(String filename, Boolean success)
   at System.Configuration.Internal.InternalConfigHost.StaticWriteCompleted(String streamName, Boolean success, Object writeContext, Boolean assertPermissions)
   at System.Configuration.Internal.InternalConfigHost.System.Configuration.Internal.IInternalConfigHost.WriteCompleted(String streamName, Boolean success, Object writeContext, Boolean assertPermissions)
   at System.Configuration.Internal.DelegatingConfigHost.WriteCompleted(String streamName, Boolean success, Object writeContext, Boolean assertPermissions)
   at System.Configuration.ClientSettingsStore.ClientSettingsConfigurationHost.WriteCompleted(String streamName, Boolean success, Object writeContext)
   at System.Configuration.UpdateConfigHost.WriteCompleted(String streamName, Boolean success, Object writeContext)
   at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
   at System.Configuration.Configuration.SaveAsImpl(String filename, ConfigurationSaveMode saveMode, Boolean forceSaveAll)
   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
   --- End of inner exception stack trace ---
   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
   at System.Configuration.LocalFileSettingsProvider.SetPropertyValues(SettingsContext context, SettingsPropertyValueCollection values)
   at System.Configuration.SettingsBase.SaveCore()
   at System.Configuration.SettingsBase.Save()
   at System.Configuration.ApplicationSettingsBase.Save()
   at AnyStatus.DefaultSettingsProvider.Save()
   at AnyStatus.SettingsStore.Save()
   at AnyStatus.SettingsStore.Save(ISettings settings)
   at AnyStatus.ImportSettings.Handler.Handle(Request request, CancellationToken cancellationToken)
```
Popup message
```
---------------------------
AnyStatus
---------------------------
Oops! An error occurred in AnyStatus 2.3.22

Unable to save config to file 'C:\Users\matth\AppData\Local\AnyStatus\anystatus.desktop.exe_StrongName_t5dzl52jcd1fnyp34mfu0q5i0vqilrtv\1.0.0.0\user.config'.
---------------------------
OK   
---------------------------
```

**Comment by MatthewSteeples** [comment]
PS Application is installed through the Store. Version 2.3.22

**Comment by MatthewSteeples** [comment]
Restarting didn't resolve the bug, but uninstalling and re-installing did. I understand if you want to close this without doing anything about it :)

**Comment by AlonAm** [comment]
Thanks for reporting. Will check.

**Comment by AlonAm** [comment]
It may occur due to some file system issue. I will close it for now but keep it for future reference.
I've created a new issue for improving exception handling #150
Thank you for posting the error message.
