### ISSUE TITLE
Error message on startup

### ISSUE THREAD

**Issue by shaneh20** [AnyStatus/Support#176]
Hi, in v2.9.3 there is an error message that displays each time AnyStatus starts up:

![image](https://user-images.githubusercontent.com/5875099/70583714-7a961f00-1c0e-11ea-8f78-5e3bcba05cec.png)

The Activity Log contains:

```
[12:05:15] Starting AnyStatus...
[12:05:15] Oops! An error occurred in AnyStatus 2.9.3
[11:20:58] System.Exception: Failed to transform pixels.
   at AnyStatus.Desktop.DockingWindow.RealPixelsToWpf(Visual visual, Point point)
   at AnyStatus.Desktop.DockingWindow.Dock()
   at AnyStatus.Desktop.MainWindow.Initialize()
   at AnyStatus.Desktop.ShowDashboard.Handler.HandleCore(Request request)
   at AnyStatus.API.RequestHandler`1.Handle(TRequest request, CancellationToken cancellationToken)
   at AnyStatus.RequestHandlerWrapperImpl`1.<>c__DisplayClass0_0.<<Handle>g__Handler|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AnyStatus.ValidationBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AnyStatus.DefaultErrorHandler`2.<Handle>d__3.MoveNext()
```

Once I click OK to clear the error and then click the AnyStatus icon in the system tray to display it, the AnyStatus window is in the middle of the screen instead of docked to the right as expected. When I click the 'dock' arrow icon it then docks AnyStatus correctly to the right and everything is ok then.

- I'm running Win 10 Pro Build 1909.
- I have two monitors.

Thanks

**Comment by AlonAm** [comment]
Thank you for reporting
