### ISSUE TITLE
TFS: Exception when updating build definition that has no build history

### ISSUE THREAD

**Issue by dee-see** [AnyStatus/Support#19]
I have added an item to my AnyStatus build monitor for a build definition that has not run yet. When starting VS this error is printed in the output window.

```
[11:02:19.207] An error occurred while updating "BUILD NAME HERE". Exception:
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at AnyStatus.TfsBuildMonitor.<GetBuildDetailsAsync>d__1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at AnyStatus.TfsBuildMonitor.Handle(TfsBuild item)
---> (Inner Exception #0) System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at AnyStatus.TfsBuildMonitor.<GetBuildDetailsAsync>d__1.MoveNext()<---
```

**Comment by AlonAm** [comment]
I'll release a fix for this soon.
Thank you

**Comment by AlonAm** [comment]
@dee-see, is this still happening in 1.4.101? no sure whether I've fixed it or not...

**Comment by dee-see** [comment]
I don't have build definitions without runs anymore, I can't tell.
