### ISSUE TITLE
Bug: Cannot trigger non-parameterized builds on Jenkins

### ISSUE THREAD

**Issue by jessejacob** [AnyStatus/Support#41]
Related to #33 the desktop app is still unable to trigger a remote build, but now it throws a 500 exception instead of a 403. The desktop app doesn't support copy/paste from the activity log and I don't have time to transcribe, so I'm attaching a screenshot rather than the text of the error.

![image](https://user-images.githubusercontent.com/2250131/30760982-41d9e1dc-9fa2-11e7-94f7-7b855e5abdd1.png)

I created a new AnyStatus item as per #33 with the CSRF flag checked (CSRF is enabled on the Jenkins server).

**Comment by AlonAm** [comment]
Thanks for the feedback. I'm looking into it...
500 indicates an internal error on Jenkins, if you can get the error message from Jenkins, that would be very helpful.

**Comment by AlonAm** [comment]
#42

**Comment by AlonAm** [comment]
I will add some logs of the actual response from the server when receiving 500, hope that would shed some light.

**Comment by jessejacob** [comment]
While I didn't see anything new in the activity log of the desktop client, I checked the Jenkins server log and it looks you're issuing a parameterized build request on any job triggered with CSRF crumb. This is an error when the build isn't parameterized, e.g.:

`Error while serving http://{myserverUrl}/job/{myJobName}/buildWithParameters
java.lang.IllegalStateException: This build is not parameterized!
	at jenkins.model.ParameterizedJobMixIn.doBuildWithParameters(ParameterizedJobMixIn.java:224)
	at hudson.model.AbstractProject.doBuildWithParameters(AbstractProject.java:1792)
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
Caused: java.lang.reflect.InvocationTargetException
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:347)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:129)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
	at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:248)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:138)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:80)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.success(BasicHeaderProcessor.java:139)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:81)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
`
You shouldn't be using parameters for the crumb, but instead using headers, I believe. See: https://stackoverflow.com/questions/43321489/how-to-add-crumb-for-csrf-in-jenkins-via-json-js

Thanks!

**Comment by AlonAm** [comment]
Thank you for taking the time to investigate the issue, your help is greatly appreciated.
It looks like the problem is not the crumb (CSRF) request, but the actual trigger request which always calls the "buildWithParameters" API even if the build does not have parameters.
I'll try to fix and release it asap.
Thanks!

**Comment by AlonAm** [comment]
Still looking for ways to solve the issue.
The problem is that Jenkins provides two different APIs for triggering parameterized and non-parameterized builds.

The preferred solution is to automatically detect whether the build is parameterized and call the appropriate API when triggering builds.

Alternatively, add a "Parameterized Build" property to the plugin to indicate the build type.

Any help to achieve the first solution would be highly appreciated.

Thanks

**Comment by AlonAm** [comment]
@jessejacob I have released a new version of AnyStatus Desktop with a fix.
You will find a new parameter in the Jenkins Job that indicates whether the build is parameterized or not (I may remove that parameter later to let the plugin auto-detect the build type).
Please let me know if you experience any further issues. Please note I haven't had much time to test it. 
Thanks

**Comment by jessejacob** [comment]
You nailed it. CSRF is working great for triggers now. THANKS!!

**Comment by AlonAm** [comment]
Great! Thank you for your feedback!
